apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    livenessProbe: # Define liveness probe
      httpGet:
        path: /index.html # check index.html on port 80
        port: 80
      initialDelaySeconds: 15 # wait 15 seconds, eg may take a sec for the pod to come up
      timeoutSeconds: 2
      periodSeconds: 5 # check every 5 seconds
      failureThreshold: 1 # allow one failure, before failing the pod
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 1