apiVersion: v1 # K api version
kind: Pod #type of K resource
metadata:
  name: my-nginx
  labels: # labels can link resources to eachother
    app: nginx
    rel: stable
spec: # the spec/blueprint for the pod
  containers: # info about the containers that will run in the pod
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80 # default port is 80, so this is overkill, but shows you can define the internal port here as well